[project]
name = "monkeybusiness"
requires-python = ">=3.12"
version="0"
dependencies = [
    "fastapi>=0.128.0",
    "kbinxml>=2.0",
    "pycryptodomex>=3.23.0",
    "python-multipart>=0.0.21",
    "tinydb>=4.8.2",
    "uvicorn[standard]>=0.40.0",
]
